
services:
  nodejs:
    image: "node:20.12-bookworm"
    container_name: app-nodejs-bookworm
    # restart: always
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    ports:
      - 5173:5173 #vue
    volumes:
      - ./:/home/node/app
    tty: true
    # package.json "scripts": {"dev": "vite --host"}
    # command: sh -c "npm install && npm run dev"
    command: sh -c "npm install && npm run build"
